# The location of the expat directory
CC=gcc  
LEX=lex  
LEXFLAGS=-lfl

TARS=RAxML-7.1.0.tar hmmer-2.3.2.tar last-278.tar prodigal.v2_00.tar rpkm.tar trnascan.tar wise2.2.0.tar
SUBDIRS=RAxML-7.1.0 hmmer-2.3.2 last-278 prodigal.v2_00 rpkm trnascan wise2.2.0


buildall:
	$(MAKE) -C trnascan 
	$(MAKE) -C rpkm 
	$(MAKE) -C wise2.2.0/src all
	$(MAKE) -C RAxML-7.1.0 -f Makefile.gcc all
	$(MAKE) -C prodigal.v2_00 all
	$(MAKE) -C last-278/src all
	$(MAKE) -C hmmer-2.3.2

cleanall:
	$(MAKE) -C trnascan clean
	$(MAKE) -C rpkm clean
	$(MAKE) -C wise2.2.0/src clean
	$(MAKE) -C RAxML-7.1.0 -f Makefile.gcc clean
	$(MAKE) -C prodigal.v2_00 clean
	$(MAKE) -C last-278/src clean
	$(MAKE) -C hmmer-2.3.2 clean

unzip: $(TARS)
	$(foreach tar, $(TARS), tar -xvf $(tar);)

cleanunzip:
	rm -rf $(SUBDIRS)
